export enum Event {
  DELETE_ONE_BODY = 'DELETE_ONE_BODY',
  CHANGE_COLOR = 'CHANGE_COLOR',
  CHOOSE_GECKO_BODY = 'CHOOSE_GECKO_BODY',
  CHOOSE_HOLE = 'CHOOSE_HOLE',
  
  INIT_MENU = 'INIT_MENU',
  EDIT_LEVEL = 'EDIT_LEVEL',
  OPEN_MENU = 'OPEN_MENU',

  ON_CHANGE_GECKO_TO_SPECIAL = 'ON_CHANGE_GECKO_TO_SPECIAL',
  FLIP_CONNECTED_GECKO_REVERSE = 'FLIP_CONNECTED_GECKO_REVERSE',
  ON_CHANGE_HOLE_TO_SPECIAL = 'ON_CHANGE_HOLE_TO_SPECIAL',
  SHOW_SPECIAL_GECKO_POPUP = 'SHOW_SPECIAL_GECKO_POPUP',
  SHOW_SPECIAL_HOLE_POPUP = 'SHOW_SPECIAL_HOLE_POPUP',
  SHOW_MULTI_HOLE_POPUP = 'SHOW_MULTI_HOLE_POPUP',
  SHOW_POPUP_STACK_GECKO = 'SHOW_POPUP_STACK_GECKO',
  SHOW_ADD_PROPERTIES_POPUP = 'SHOW_ADD_PROPERTIES_POPUP',
  SHOW_MOVABLE_BOX_POPUP = 'SHOW_MOVABLE_BOX_POPUP',
  SHOW_DESIGN_ERROR_POPUP = 'SHOW_DESIGN_ERROR_POPUP',
  UPDATE_VIEW_PROPERTIES = 'UPDATE_VIEW_PROPERTIES',

  UPDATE_COVERED_CELLS = 'UPDATE_COVERED_CELLS',
}
