export enum Event {
  DELETE_ONE_BODY = 'DELETE_ONE_BODY',
  CHANGE_COLOR = 'CHANGE_COLOR',
  CHOOSE_GECKO_BODY = 'CHOOSE_GECKO_BODY',
  CHOOSE_HOLE = 'CHOOSE_HOLE',
  
  INIT_MENU = 'INIT_MENU',
  EDIT_LEVEL = 'EDIT_LEVEL',
  OPEN_MENU = 'OPEN_MENU',

  ON_CHANGE_GECKO_TO_SPECIAL = 'ON_CHANGE_GECKO_TO_SPECIAL',
  SHOW_SPECIAL_GECKO_POPUP = 'SHOW_SPECIAL_GECKO_POPUP',
  OPEN_POPUP_STACK_GECKO = 'OPEN_POPUP_STACK_GECKO',
}
