export enum Event {
  DELETE_ONE_BODY = 'DELETE_ONE_BODY',
  CHANGE_COLOR = 'CHANGE_COLOR',
  CHOOSE_GECKO_BODY = 'CHOOSE_GECKO_BODY',
  CHOOSE_HOLE = 'CHOOSE_HOLE',
  
  INIT_MENU = 'INIT_MENU',
  EDIT_LEVEL = 'EDIT_LEVEL',
  OPEN_MENU = 'OPEN_MENU',

  OPEN_POPUP_STACK_GECKO = 'OPEN_POPUP_STACK_GECKO',
  
}